use_frameworks!

target 'NNHealth_Example' do
  pod 'NNHealth', :path => '../'

  target 'NNHealth_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
